# Generated by Django 4.2.3 on 2023-07-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='Region',
            new_name='region',
        ),
    ]
