# Generated by Django 4.2.3 on 2023-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0002_rename_region_tienda_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
