# Generated by Django 4.2.3 on 2023-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0004_alter_producto_cantidad_alter_producto_precioventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
